name: devpropertyhub
description: A Flutter application for property developers with Material Design principles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.0.5
  
  # Routingflutter pub getflutter pub getflutter pub get
  go_router: ^7.0.0
  
  # UI Components
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  
  # Network
  connectivity_plus: ^4.0.1
  dio: ^5.1.2
  http: ^0.13.6
  
  # Storage
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.1
  
  # Utilities
  intl: ^0.18.1
  logger: ^1.3.0
  url_launcher: ^6.1.11
  
  # Forms
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

# Override dependencies to resolve conflicts
dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  # Fonts
  # Using Google Fonts package so we don't need to declare fonts here
