name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Format (enforce code style)
      run: dart format --set-exit-if-changed lib test

    - name: Analyze
      run: flutter analyze

    - name: Run tests
      run: flutter test
